services:
  stock-analyst:
    image: ghcr.io/krbob/stock-analyst:main
    ports:
      - "7777:7777"
    depends_on:
      - stock-analyst-backend
    environment:
      - BACKEND_URL=http://stock-analyst-backend:7776
    restart: unless-stopped

  stock-analyst-backend:
    image: ghcr.io/krbob/stock-analyst-backend:main
    restart: unless-stopped
