services:
  stock-analyst:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7777:7777"
    depends_on:
      - stock-analyst-backend
    environment:
      - BACKEND_URL=http://stock-analyst-backend:7776
    restart: unless-stopped

  stock-analyst-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "7776:7776"
    restart: unless-stopped
