services:
  stock-analyst:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - stock-analyst-backend
    environment:
      - BACKEND_URL=http://stock-analyst-backend:8081
    restart: unless-stopped

  stock-analyst-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    restart: unless-stopped
